# Generated by Django 2.2 on 2019-04-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_note_unique_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='unique_words',
        ),
    ]
