# Generated by Django 2.2 on 2019-04-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_remove_note_unique_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
