# Generated by Django 2.2 on 2019-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_note_unique_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
